

allCities = dict()

allCities['madrid'] = 'b'
allCities['montreal'] = 'b'
allCities['paris'] = 'b'
allCities['newyork'] = 'b'
allCities['stpetersburg'] = 'b'
allCities['essen'] = 'b'
allCities['sanfrancisco'] = 'b'
allCities['atlanta'] = 'b'
allCities['chicago'] = 'b'
allCities['washington'] = 'b'
allCities['london'] = 'b'
allCities['milan'] = 'b'

allCities['saopaulo'] = 'y'
allCities['miami'] = 'y'
allCities['johannesburg'] = 'y'
allCities['bogota'] = 'y'
allCities['losangeles'] = 'y'
allCities['mexicocity'] = 'y'
allCities['lima'] = 'y'
allCities['santiago'] = 'y'
allCities['kinshasa'] = 'y'
allCities['khartoum'] = 'y'
allCities['lagos'] = 'y'
allCities['buenosaires'] = 'y'

allCities['baghdad'] = 'bk'
allCities['kolkata'] = 'bk'
allCities['istanbul'] = 'bk'
allCities['karachi'] = 'bk'
allCities['algiers'] = 'bk'
allCities['cairo'] = 'bk'
allCities['mumbai'] = 'bk'
allCities['delhi'] = 'bk'
allCities['moscow'] = 'bk'
allCities['riyadh'] = 'bk'
allCities['chennai'] = 'bk'
allCities['tehran'] = 'bk'

allCities['taipei'] = 'r'
allCities['beijing'] = 'r'
allCities['hochiminhcity'] = 'r'
allCities['tokyo'] = 'r'
allCities['manila'] = 'r'
allCities['hongkong'] = 'r'
allCities['bangkok'] = 'r'
allCities['seoul'] = 'r'
allCities['osaka'] = 'r'
allCities['jakarta'] = 'r'
allCities['shanghai'] = 'r'
allCities['sydney'] = 'r'

events = ['airlift', 'governmentgrant', 'airlift','onequietnight','forecast','resilientpopulation']
